services:
  haproxy:
    image: haproxy:1.7.9
    container_name: haproxy
    ports:
      - "8080:1080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  backend:
    build: ./node/.
    ports:
      - "3000:3000"