services:

  haproxy:
    image: haproxy:1.7.9
    container_name: haproxy
    ports:
      - "8080:1080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  # proxy:
  #   image: python:3.11-slim
  #   container_name: proxy
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./proxy:/app
  #   working_dir: /app
  #   command: python web_proxy.py

  # frontend:
  #   image: httpd:2.2
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
  #     - ./apache/.htpasswd:/usr/local/apache2/conf/.htpasswd
  #     - ./apache/.htgroups:/usr/local/apache2/conf/.htgroups
  #   depends_on:
  #     - backend

  backend:
    build: ./node/.
    ports:
      - "3000:3000"

  # traffic:
  #   image: python:3.11-slim
  #   volumes:
  #     - ./traffic:/workspace
  #   working_dir: /workspace
  #   command: sh -c "pip install -r requirements.txt && python traffic.py"

  # nginx:
  #   image: nginx:1.17.6
  #   ports:
  #     - "81:81"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/.htpasswd:/etc/nginx/.htpasswd
  #   depends_on:
  #     - backend
